### ISSUE TITLE
loyalty card images confusion

### ISSUE THREAD

**Issue by davidlehn** [credential-handler/vc-examples#41]
The customer-loyalty setup shows a BIG RETAIL image for the card.  The issuer data uses the retail-coupon BIG MEGA logo.  It's a bit confusing to issue using the BIG RETAIL image, then, for instance, on the vc playground doing a verify and seeing BIG MEGA issuer image instead on the selection screen.  I'm not sure what should be shown and how, but the current setup can be confusing.

**Comment by BigBlueHat** [comment]
This was addressed in 6289dde463b3856363c786c06da54b0feacc41e9
